version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sales
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../data/db:/docker-entrypoint-initdb.d

  marquez:
    image: marquezproject/marquez:0.28.0
    container_name: marquez
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - MARQUEZ_HOST=0.0.0.0
      - MARQUEZ_PORT=5000
      - MARQUEZ_POSTGRES_HOST=postgres
      - MARQUEZ_POSTGRES_PORT=5432
      - MARQUEZ_POSTGRES_DATABASE=marquez
      - MARQUEZ_POSTGRES_USER=user
      - MARQUEZ_POSTGRES_PASSWORD=password

  marquez-web:
    image: marquezproject/marquez-web:0.28.0
    container_name: marquez-web
    depends_on:
      - marquez
    ports:
      - "3000:3000"
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5000

  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  jobmanager:
    image: apache/flink:1.14.4-scala_2.12-java11
    container_name: jobmanager
    ports:
      - "8081:8081"
      - "9249:9249"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        openlineage.url: http://marquez:5000
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9249
    volumes:
      - ../ingestion/target/ingestion-1.0-SNAPSHOT.jar:/opt/flink/lib/ingestion.jar
      - ../ingestion/target/openlineage-flink-0.10.0.jar:/opt/flink/lib/openlineage-flink.jar
      - ../processing/target/processing-1.0-SNAPSHOT.jar:/opt/flink/lib/processing.jar
      - ../storage/target/storage-1.0-SNAPSHOT.jar:/opt/flink/lib/storage.jar


  taskmanager:
    image: apache/flink:1.14.4-scala_2.12-java11
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    ports:
      - "9250:9250"
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        openlineage.url: http://marquez:5000
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        metrics.reporter.prom.port: 9250
    volumes:
      - ../ingestion/target/ingestion-1.0-SNAPSHOT.jar:/opt/flink/lib/ingestion.jar
      - ../ingestion/target/openlineage-flink-0.10.0.jar:/opt/flink/lib/openlineage-flink.jar
      - ../processing/target/processing-1.0-SNAPSHOT.jar:/opt/flink/lib/processing.jar
      - ../storage/target/storage-1.0-SNAPSHOT.jar:/opt/flink/lib/storage.jar

volumes:
  postgres_data:
